email:
  sender: "ADD YOUR EMAIL HERE"
  sender_password: "ADD YOUR PASSWORD HERE"

streamlit:
  title: "Roam Rover"
  icon: "✈️"

data:
  Jordan: "Data/Jordan Dataset.csv"
  UAE: "Data/UAE Dataset.csv"

llm:
  api_key: "ADD YOUR API KEY HERE"
