# import getpass
import smtplib
from email.message import EmailMessage
import yaml

with open("config.yaml", "r") as file:
    config_data = yaml.safe_load(file)


async def send_mail(plan: str, user_email: str):
    """a function to send an email to the user with the plan generated by the bot.

    Args:
        plan (str): the plan generated by the bot.
        user_email (str): the email provided by the user.
    """
    try:
        email_sender = config_data["email"]["sender"]
        email_pass = config_data["email"]["sender_password"]
        email_rec = user_email

        sub = "Roam Rover Itinerary"
        body = plan

        em = EmailMessage()
        em["From"] = email_sender
        em["To"] = email_rec
        em["Subject"] = sub

        em.set_content(body)

        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
            smtp.login(email_sender, email_pass)
            smtp.sendmail(email_sender, email_rec, em.as_string())
    except Exception as e:
        print(e)
